vlingo/xoom-schemata

- src/main/frontend/src/components/Schemata.vue
- src/main/frontend/src/views/Schemata.vue
Closes #28.
Makes treeview nodes load and open on the first click.
Reason was a nested `Promise` that snuck in undetected.
> Clean up nested promises and refactor error handling

- src/main/frontend/src/App.vue
- src/main/frontend/src/api/SchemataRepository.js
- src/main/frontend/src/components/Schema.vue
- src/main/frontend/src/components/SchemaVersion.vue
- src/main/frontend/src/router.js
- src/test/resources/rest-api-calls.http
This completes the creation dialogs.
We can now create Orgs, Units, Contexts, Schemata and Schema Versions.
There are still some issues regarding usability (see #35 and #34) as well as some refactorings that still need to be done (see #36 and #33) as well as one validation issue in the backend (#31)
But overall, this can be demo'ed, IMHO.
> Add creation dialogs for schema and schema version

- Dockerfile
The docker image supports switching environments with this PR.
You can now run the image by `docker run -e VLINGO_ENV=prod -p9019:9019 vlingo/vlingo-schemata` to use `src/main/resources/vlingo-schemata-prod.properties`.
`VLINGO_ENV` defaults to `dev`
> Support specifying the runtime environment

- README.md
- src/main/frontend/package-lock.json
- src/main/frontend/package.json
- src/main/frontend/src/components/SchemaVersion.vue
- src/main/frontend/vue.config.js
- src/test/e2e/cypress/integration/browse-schemata.spec.ts
- src/test/e2e/cypress/integration/entity-creation.spec.ts
- src/test/e2e/cypress/support/commands.ts
- src/test/e2e/cypress/support/index.d.ts
Closes #34 
Use Monaco Editor (https://microsoft.github.io/monaco-editor/) via `monaco-editor-vue` as specification and description editor in the schema version create dialog.
Uses `markdown` highlighting for the description (see also #47) and `javascript` highlighting for specifications. This is not really correct, but works fine with the schema grammar until we provide a custom highlighter.
> Use monaco editor for specification and description

- .circleci/config.yml
Adds the CircleCI config to build the docker image and push it to https://hub.docker.com/r/vlingo/vlingo-schemata.
Images are only built on `master` and always tagged `:latest`.
To enable the build in CircleCI the following steps are neccessary.
However, this PR can be merged, it won't do anything if the project is not yet enabled.
* Enable the project (`Set Up Project`) in CircleCI at https://circleci.com/add-projects/gh/vlingo
* Ingore the instructions (build is already set up in `.circleci/config.yml`) and click the `Start Building` button
* Go to the project settings at https://circleci.com/gh/vlingo/vlingo-schemata/edit#env-vars and add two env vars:
* `DOCKER_TOKEN` -> can be created at https://hub.docker.com/settings/security
* `DOCKER_USER` -> the docker hub user 
I'm lacking the …
> Build docker image on CircleCI & push to Docker Hub

- .circleci/config.yml
- Dockerfile
- src/test/e2e/.gitignore
- src/test/e2e/config.json
- src/test/e2e/cypress.json
- src/test/e2e/cypress/integration/entity-creation.spec.ts
- src/test/e2e/package-lock.json
- src/test/e2e/package.json
Enables ...
* ... starting the server built in previous build steps,
* ... running the E2E tests against it,
* ... displaying the test results & screenshots of failed tests in CircleCI and
* ... making videos of the test runs available on CircleCI
It also disables as many `.m2` caches as it can (within CircleCI and in Docker layers) b/c of the non `-SNAPSHOT` versioning scheme. Once this is in place, we should re-enable caching to get _much_ faster builds.
Closes #32
> Enable E2E tests on CircleCI

- docker-compose.yaml
- src/main/java/io/vlingo/schemata/infra/persistence/PostgresSchemataObjectStore.java
- src/main/java/io/vlingo/schemata/resource/CodeResource.java
- src/test/resources/rest-api-calls.http
Makes it possible to retrieve Java code from `CodeResource`.
Please note that this disables the authentication checks by providing a matching fake auth if none is given. All workaround related sections in the code are marked w/ `FIXME` comments.
Relates to #55.
> Allow for retrieving Java code for schemas via the http API

- src/main/frontend/package-lock.json
- src/main/frontend/package.json
- src/main/frontend/src/api/SchemataRepository.js
- src/main/frontend/src/components/Properties.vue
- src/main/frontend/src/components/SchemaVersion.vue
- src/main/frontend/src/components/Schemata.vue
- src/main/frontend/src/components/Versions.vue
- src/main/frontend/src/store.js
- src/main/frontend/vue.config.js
- src/main/java/io/vlingo/schemata/infra/persistence/HSQLDBSchemataObjectStore.java
- src/main/java/io/vlingo/schemata/infra/persistence/PostgresSchemataObjectStore.java
- src/main/java/io/vlingo/schemata/resource/SchemaVersionResource.java
- src/test/e2e/cypress/integration/browse-schemata.spec.ts
- src/test/e2e/cypress/integration/entity-creation.spec.ts
- src/test/e2e/cypress/integration/schema-version-maintenance.spec.ts
- src/test/e2e/cypress/integration/validation.spec.ts
- src/test/java/io/vlingo/schemata/infra/persistence/SchemataObjectStoreTest.java
- src/test/java/io/vlingo/schemata/resource/SchemaVersionResourceTest.java
Merge after #74 
Closes #72 
Known issues: #77, #78
> Show & download generated java sources

- src/main/frontend/package-lock.json
- src/main/frontend/src/api/SchemataRepository.js
- src/main/frontend/src/components/Context.vue
- src/main/java/io/vlingo/schemata/infra/persistence/SchemataObjectStore.java
- src/main/java/io/vlingo/schemata/query/SchemaVersionQueries.java
- src/main/java/io/vlingo/schemata/query/SchemaVersionQueriesActor.java
- src/test/e2e/cypress/integration/entity-updates.spec.ts
- src/test/e2e/cypress/support/commands.ts
- src/test/java/io/vlingo/schemata/infra/persistence/SchemataObjectStoreTest.java
* Makes use of the new `redefineWith` handlers for updates.
* Makes E2E update tests more robust
* Fixes `Schema` updates not being persisted
* Enables all previously ignored/skipped tests
Closes #86 
Closes #90 
Closes #69
> Use redefine handlers for organizations, units, contexts and schemas

- src/main/frontend/src/components/Schemata.vue
- src/test/e2e/cypress/integration/browse-schemata.spec.ts
Adds a refresh button to the schemata treeview that reloads all organizations.
Closes #99
> Add refresh button to schemata view

- src/main/java/io/vlingo/schemata/Bootstrap.java
- src/main/java/io/vlingo/schemata/Schemata.java
- src/main/java/io/vlingo/schemata/codegen/backend/java/JavaBackend.java
- src/main/java/io/vlingo/schemata/model/FullyQualifiedReference.java
- src/main/java/io/vlingo/schemata/query/SchemaQueries.java
- src/main/java/io/vlingo/schemata/query/SchemaQueriesActor.java
- src/main/java/io/vlingo/schemata/resource/SchemaVersionResource.java
- src/test/java/io/vlingo/schemata/codegen/specs/JavaCodeGenTests.java
- src/test/java/io/vlingo/schemata/model/FullyQualifiedReferenceTest.java
- src/test/java/io/vlingo/schemata/resource/JavaCodeResourceTest.java
- src/test/resources/schemata-demo.http
Adds operation to push a new schema version using the fully qualified reference, e.g.
```
POST http://localhost:9019/versions/Vlingo:schemata:io.vlingo.schemata:SchemaDefined:0.0.1
Content-Type: application/json
{
"description": "Updated revision.",
"specification": "event SchemaDefined { type eventType }",
"previousVersion": "0.0.0"
}
```
Focuses on the happy path for the demo, we should review error handling later on.
Part of #105
> Allow for pushing new schema versions

- src/main/java/io/vlingo/schemata/query/SchemaVersionQueriesActor.java
- src/main/java/io/vlingo/schemata/resource/SchemaVersionResource.java
- src/test/resources/rest-api-calls.http
Adds 
* API endpoint `GET /versions/{reference}` returning schema version data
* API endpoint `GET /versions/{reference}/status` returning schema version state
Required for validation in `vlingo-build-plugins` `PullSchemataMojo`
> Support pulling schema versions by reference

- src/main/frontend/package-lock.json
- src/main/frontend/package.json
- src/main/java/io/vlingo/schemata/resource/SchemaVersionResource.java
- src/main/java/io/vlingo/schemata/resource/data/SchemaVersionData.java
- src/test/e2e/cypress/integration/entity-creation.spec.ts
- src/test/e2e/cypress/integration/validation.spec.ts
- src/test/e2e/cypress/plugins/index.js
- src/test/e2e/package-lock.json
- src/test/e2e/package.json
- src/test/java/io/vlingo/schemata/resource/ExtendedResourceTest.java
- src/test/resources/schemata-demo.http
- Allows pushing updates only if the previous version exists or is `0.0.0`
- Update JS dependencies in frontend and e2e tests
- Don't hang when trying to push an incompatible schema through the `/versions/<reference>` endpoint
Closes #126
> Version update handling fixes

- .circleci/config.yml
These tests were implemented for the previous version of the UI and will be removed.
> Do not run the legacy e2e tests on circleci

- src/main/java/io/vlingo/schemata/infra/persistence/StateStoreProvider.java
@VaughnVernon 
This PR fixes the runtime type handling in the `StateStore` creation. Additionally, I've implemented the DB connection retry so when Schemata is running on Docker along with a production database, it won't be subject to the container's initialization order.
Thanks.
> Environment runtime type + DB Connection retry

- src/main/java/io/vlingo/xoom/schemata/query/SchemaQueries.java
- src/main/java/io/vlingo/xoom/schemata/query/SchemaQueriesActor.java
- src/main/java/io/vlingo/xoom/schemata/resource/SchemaVersionResource.java
- src/test/java/io/vlingo/xoom/schemata/query/FailingStateStore.java
- src/test/java/io/vlingo/xoom/schemata/query/SchemaQueriesTest.java
Replaces #177
I wasn't sure whether to hide retry parameters inside the query actor or pass it down from the resource. In the end, decided to go with the second option as it was useful to use lower values for these parameters in tests.
> Retry the schema query when pushing the schema version to account for eventual consistency

- .github/workflows/build.yml
- Dockerfile
- README.md
Currently, we use an outdated version of java 8.
From the OpenJDK team:
> The OpenJDK port for Alpine is not in a supported release by OpenJDK, since it is not in the mainline code base. It is only available as early access builds of OpenJDK Project Portola. See also [this comment](https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754). So this image follows what is available from the OpenJDK project's maintainers.
>
> What this means is that Alpine based images are only released for early access release versions of OpenJDK. Once a particular release becomes a "General-Availability" release, the Alpine version is dropped from the "Supported Tags"; they are still available to pull, but will no longer be updated.
* amd64
* arm64 (Apple M1)
> Revamp the docker image 

- src/main/frontend/src/components/VersionContainer.svelte
- src/main/java/io/vlingo/xoom/schemata/codegen/TypeDefinitionCompiler.java
- src/main/java/io/vlingo/xoom/schemata/codegen/template/schematype/SchemaTypeTemplateData.java
- src/main/java/io/vlingo/xoom/schemata/codegen/template/schematype/csharp/CSharpSchemaTypeTemplateData.java
- src/main/java/io/vlingo/xoom/schemata/codegen/template/schematype/csharp/CSharpSchemaTypeTemplateParameter.java
- src/main/java/io/vlingo/xoom/schemata/codegen/template/schematype/java/JavaSchemaTypeTemplateData.java
- src/main/resources/codegen/c_sharp/SchemaType.ftl
- src/test/java/io/vlingo/xoom/schemata/codegen/specs/CSharpCodeGenTests.java
- src/test/resources/text-expectations/c_sharp/all-single-types.text
- src/test/resources/text-expectations/c_sharp/basic-arrays-with-default-values.text
- src/test/resources/text-expectations/c_sharp/basic-arrays.text
- src/test/resources/text-expectations/c_sharp/basic-with-default-values.text
- src/test/resources/text-expectations/c_sharp/basic-with-package.text
- src/test/resources/text-expectations/c_sharp/basic.text
- src/test/resources/text-expectations/c_sharp/computed-only.text
- src/test/resources/text-expectations/c_sharp/minimal.text
- src/test/resources/text-expectations/c_sharp/price-changed.text
> Generate C# domain events

- src/main/antlr4/io/vlingo/xoom/schemata/codegen/antlr/SchemaVersionDefinitionLexer.g4
- src/main/antlr4/io/vlingo/xoom/schemata/codegen/antlr/SchemaVersionDefinitionParser.g4
- src/main/java/io/vlingo/xoom/schemata/codegen/ast/types/ComplexType.java
- src/main/java/io/vlingo/xoom/schemata/codegen/parser/AntlrTypeParser.java
- src/test/java/io/vlingo/xoom/schemata/codegen/specs/JavaCodeGenTests.java
- src/test/resources/io/vlingo/xoom/schemata/codegen/vss/price-changed.vss
Re #183
Replaces #191
* The type identifier only allows for letters and digits
* The complex type attributes can only be made of category type references (i.e. `data.Price`).
* The category is currently not validated (i.e. `data.Price` could actually be referenced as `event.Price`).
* One of the tests that used to use fully qualified type names was updated to use category type references.  Fully qualified type references are no longer supported.
* Arrays of complex types are currently not supported (never were). I'll add it in a separate PR.
* The version in type reference doesn't seem to have any effect. Something for a separate PR too.
> Fix schema definitons with complex type references

- src/main/java/io/vlingo/xoom/schemata/codegen/template/schematype/SchemaTypePackage.java
- src/main/java/io/vlingo/xoom/schemata/codegen/template/schematype/csharp/CSharpSchemaTypeTemplateData.java
- src/main/java/io/vlingo/xoom/schemata/codegen/template/schematype/csharp/CSharpType.java
- src/main/java/io/vlingo/xoom/schemata/codegen/template/schematype/java/JavaSchemaTypeTemplateData.java
- src/test/java/io/vlingo/xoom/schemata/codegen/specs/CodeGenSpecs.java
- src/test/resources/io/vlingo/xoom/schemata/codegen/vss/command.vss
- src/test/resources/text-expectations/c_sharp/command.text
- src/test/resources/text-expectations/java/command.text
Example:
```
command ChangePrice {
data.Price oldPrice
data.Price:1.0.0 newPrice
}
```
Java
```java
package io.vlingo.xoom.examples.command;
import io.vlingo.xoom.examples.data.Price;
import io.vlingo.xoom.lattice.model.Command;
public final class ChangePrice extends Command {
public final Price oldPrice;
public final Price newPrice;
public ChangePrice(final Price oldPrice, final Price newPrice) {
this.oldPrice = oldPrice;
this.newPrice = newPrice;
}
}
```
C#
```csharp
using Io.Vlingo.Xoom.Examples.Data;
using Vlingo.Lattice.Model;
namespace Io.Vlingo.Xoom.Examples.Commands
{
public sealed class ChangePrice : Command
{
public Price OldPrice { get; }
public Price NewPrice { get; }
public ChangePrice(Price oldPrice, Price newPrice) {
OldPrice = oldPrice;
NewPrice = newPrice;
}
}
}
```
> Generate command types

- src/main/java/io/vlingo/xoom/schemata/infra/persistence/StateStoreProvider.java
- src/main/java/io/vlingo/xoom/schemata/query/view/OrganizationView.java
- src/main/java/io/vlingo/xoom/schemata/query/view/UnitView.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/CodeProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/ContextProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/ContextsProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/Fixtures.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/NamedSchemaProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/OrganizationProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/OrganizationsProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/ProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/SchemaProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/SchemaVersionProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/SchemaVersionsProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/SchemasProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/UnitProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/infra/persistence/UnitsProjectionTest.java
- src/test/java/io/vlingo/xoom/schemata/test/Assertions.java
- src/test/java/io/vlingo/xoom/schemata/test/symbio/FakeStateStoreDispatcher.java
When trying to add a new projection I noticed projections are mostly tested in resource tests. Scope of such tests is quite wide.
I also noticed that when many entities are projected in a single test, projections tend to be created "out of order". This sometimes leads to failing tests. For example, CodeView cannot be created before SchemaView is persisted first. This wouldn't normally happen in an application serving real clients, but can easily happen in tests as they operate on multiple entities almost simultaniously.
Having dedicated projection tests would make the scope of resource tests smaller and let us write more focused tests.
Below's an example of a projection test. The test will wait for a projection to create the view before proceeding to querying it: …
> Testing projections

- src/main/java/io/vlingo/xoom/schemata/codegen/TypeDependenciesRetrieverActor.java
- src/main/java/io/vlingo/xoom/schemata/infra/persistence/SchemaVersionLookUpActor.java
- src/main/java/io/vlingo/xoom/schemata/infra/persistence/SchemaVersionQueryExecutor.java
- src/main/java/io/vlingo/xoom/schemata/resource/SchemaResource.java
- src/test/java/io/vlingo/xoom/schemata/resource/AbstractRestTest.java
- src/test/java/io/vlingo/xoom/schemata/resource/SchemaDependenciesResourceTest.java
I think this has proved we should discourage (or make it impossible) for end users to use `completesEventually()` with `completes()` directly:
```java
CompletesEventually completes = completesEventually();
eventualOutcome.andFinallyConsume((R value) -> completes.with(value));
return completes();
````
and suggest using `answerFrom()` instead:
```java
return answerFrom(eventualOutcome);
```
Related PRs:
* https://github.com/vlingo/xoom-common/pull/44
* https://github.com/vlingo/xoom-actors/pull/91
> Prevent hanging of requests for schema dependencies
